server:
  port: 8080
  mode: debug  # debug, release, test

database:
  host: localhost
  port: 3306
  username: root
  password: admin888
  name: go_react_admin
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 60  # in minutes

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5

jwt:
  secret: "go-react-admin-secret-key-change-in-production"
  expiration: 24  # in hours
